In [2]:
import numpy as np

array = [1,2,3,4,5]
array2D = ([[1,2,3], [2,3,4], [3,4,5]]) #двумерный массив

print(array)
print(array2D)

[1, 2, 3, 4, 5]
[[1, 2, 3], [2, 3, 4], [3, 4, 5]]


In [3]:
array = np.arange(9)
array = array.reshape(3,3) #изменение массива в матрицу 3на3
print(array)
print(array.sum())
print(array.mean())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
36
4.0


In [4]:
zeros = np.zeros(6) #массив из нулей длинной в 6 элементов
ones = np.ones((4,4)) #матрица 4на4 из единиц
array = np.arange(-10, 10, 2).reshape(2,5) #arange(нач точка,конечная точка,шаг)
zeros, ones, array

(array([0., 0., 0., 0., 0., 0.]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[-10,  -8,  -6,  -4,  -2],
        [  0,   2,   4,   6,   8]]))

In [5]:
A = np.array([[1, 2],[5, 6]])
B = np.array([[-2, 6],[4, -5]])
print(A*B)

[[ -2  12]
 [ 20 -30]]


In [6]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print("A:\n", A)
print("\nTranspose A:\n", np.transpose(A))

A:
 [[1 2]
 [3 4]
 [5 6]]

Transpose A:
 [[1 3 5]
 [2 4 6]]


In [14]:
B = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14],
              [15, 16, 17, 18, 19],
            ])
B1 = B[:2] # срез, выбираем первые 2 столбца
B2 = B[:, 2] # срез, выбираем 3й столбец
B3 = B[2, :] # срез, выбираем 3ю строчку
B4 = 1
for i in range(0, B.shape[0], 1):
    print(B[i][1]) #индексация: каждый элемент 2го столбца
B1, B2, B3, B4

1
6
11
16


(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([ 2,  7, 12, 17]),
 array([10, 11, 12, 13, 14]),
 1)

In [10]:
array = np.random.sample(5)
print(array)
print(array.shape)
print(array.dtype) #тип переменных

[0.67704946 0.5916255  0.56941898 0.85274038 0.59420329]
(5,)
float64
