In [34]:
import numpy as np

array = [1,2,3,4,5]
array2D = ([[1,2,3], [2,3,4], [3,4,5]]) #двумерный массив

print(array)
print(array2D)

[1, 2, 3, 4, 5]
[[1, 2, 3], [2, 3, 4], [3, 4, 5]]


In [33]:
array = np.arange(9)
array = array.reshape(3,3) #изменение массива в матрицу 3на3
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
zeros = np.zeros(6) #массив из нулей длинной в 6 элементов
ones = np.ones((4,4)) #матрица 4на4 из единиц
array = np.arange(-10, 10, 2).reshape(2,5) #arange(нач точка,конечная точка,шаг)
zeros, ones, array

(array([0., 0., 0., 0., 0., 0.]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[-10,  -8,  -6,  -4,  -2],
        [  0,   2,   4,   6,   8]]))

In [42]:
A = np.array([[1, 2],[5, 6]])
B = np.array([[-2, 6],[4, -5]])
print(A*B)

[[ -2  12]
 [ 20 -30]]


In [43]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print("A:\n", A)
print("\nTranspose A:\n", np.transpose(A))

A:
 [[1 2]
 [3 4]
 [5 6]]

Transpose A:
 [[1 3 5]
 [2 4 6]]


In [47]:
array = np.random.sample(5)
print(array)
print(array.shape)
print(array.dtype) #тип переменных

[0.01201049 0.45465748 0.56358219 0.12330966 0.06170141]
(5,)
float64
